[colors.bright]
black = "0x666666"
blue = "0xb7cbf4"
cyan = "0xa9c1de"
green = "0xd8fa3b"
magenta = "0xb77ee0"
red = "0xff0000"
white = "0xeeeeee"
yellow = "0xe7c547"

[colors.normal]
black = "0x282828"
blue = "0x91aadf"
cyan = "0xb7cbf4"
green = "0x57ba37"
magenta = "0xcf73e6"
red = "0xd71a1a"
white = "0xdedede"
yellow = "0xf0d50c"

[colors.primary]
background = "0x121212"
foreground = "0xd0d0d0"

[env]
TERM = "xterm-256color"

[font]
size = 12.0

[font.bold]
family = "Space Mono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Space Mono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Space Mono Nerd Font"
style = "Italic"

[font.normal]
family = "Space Mono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = -5

[window.dimensions]
columns = 100
lines = 30
