[theme]
theme = "nord-dark"
[theme.overrides]
#idle_bg = "#9b60bf"
#idle_bg = "#0bd3d3"
idle_fg = "#00000f"
#alternating_tint_bg = "#000000"


[icons]
icons = "awesome4"
#[icons.overrides]
#music = "♪"

[[block]]
block = "music"
player = "spotify"
format = " $icon {$combo.str(max_w:60) $prev $play $next |}"
#interval = 1
[block.theme_overrides]
info_bg = "#d71a1a"
idle_bg = "#d71a1a"
good_bg = "#d71a1a"
warning_bg = "#d71a1a"
idle_fg = "#00000f"
good_fg = "#00000f"
warning_fg = "#00000f"
info_fg = "#00000f"

[[block]]
block = "sound"
step_width = 5
[block.theme_overrides]
idle_bg = "#d71a1a"
#idle_fg = "#00000f"

[[block]]
block = "uptime"
[block.theme_overrides]
idle_bg = "#f0d50c"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "
[block.theme_overrides]
idle_bg = "#f0d50c"
info_bg = "#f0d50c"
good_bg = "#f0d50c"
warning_bg = "#f0d50c"

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
[block.theme_overrides]
idle_bg = "#f0d50c"

[[block]]
block = "cpu"
interval = 1
format = " $icon $utilization "
format_alt = " $icon $frequency{ $boost|} "

[block.theme_overrides]
idle_bg = "#f0d50c"

#[[block]]
#block = "temperature"
#collapsed = false
#interval = 10
#format = "{min} min, {max} max, {average} avg"
#chip = "*-isa-*"
#inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "nvidia_gpu"
interval = 1
format = " $icon $utilization {$temperature}C"
[block.theme_overrides]
idle_bg = "#57ba37"

[[block]]
block = "speedtest"
interval = 1800
[block.theme_overrides]
idle_bg = "#91aadf"


#[[block]]
#block = "load"
#interval = 1
#format = "{1m}"

# [[block]]
# block = "weather"
# format = "{weather} {temp}F {humidity}% ({location})"
# #autolocate = true
# service = { name = "openweathermap", api_key = "", city_id = "4744709", units = "imperial" }

[[block]]
block = "weather"
format = " $icon $weather ($location) {$temp}F $humidity"
[block.service]
name = "openweathermap"
api_key = "YOUR_API_KEY"
city_id = "4744709"
units = "imperial"
[block.theme_overrides]
idle_bg = "#b7cbf4"
#idle_bg = "#ffc295"
#idle_bg = "#c96010"
#idle_fg = "#00000f"

[[block]]
block = "time"
interval = 60
[block.format]
short = " $icon $timestamp.datetime(f:%R) "
[block.theme_overrides]
idle_bg = "#cf73e6"
#idle_fg = "#00000f"

[[block]]
block = "toggle"
format = " $icon HDMI "
command_state = "xrandr | grep 'DP-2'"
command_on = "~/.config/scripts/toggle_multiple_monitors.sh 3"
command_off = "~/.config/scripts/toggle_multiple_monitors.sh 1"
interval = 5
[block.theme_overrides]
idle_bg = "#6f73e6"

[[block]]
block = "custom"
command = "echo \uf011" # assumes fontawesome icons
interval = "once"
[[block.click]]
button = "left"
cmd = "~/.config/rofi/powermenu/type-4/powermenu.sh"
[block.theme_overrides]
idle_bg = "#7f73e6"
